CREATE DATABASE IF NOT EXISTS barbearia;
USE barbearia;


CREATE TABLE IF NOT EXISTS produtos (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
preco DECIMAL(10,2) NOT NULL,
descricao TEXT NOT NULL,
estoque INT NOT NULL,
imagem VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS servicos (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
preco DECIMAL(10,2) NOT NULL,
descricao TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS agendamentos (
id INT AUTO_INCREMENT PRIMARY KEY,
servico_id INT NOT NULL,
data DATE NOT NULL,
hora TIME NOT NULL,
observacoes TEXT,
FOREIGN KEY (servico_id) REFERENCES servicos(id)
);

